on:
  push:
jobs:
  build:
    name: Hello world
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Write a multi-line message
        run:  echo "changes pushed"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '12'


      - name: Install Dependencies
        run: npm ci

      - name: Remove .next
        run: rm -rf .next

      - name: Running test
        run: node test.js

        

      - name: Running next
        run: npm run dev
       
